name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: Kemeow0815/social-readme@master
        with:
          blog_rss_link: https://blog.kemeow.top/rss.xml
          blog_limit: 5 # blog数量
          commit_message: Updated social rss by social-readme # commit说明
          # douban_name: znyalor
